# Generated by Django 2.2.14 on 2020-07-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bella', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
    ]
